- app/controllers/bookings_controller.rb
- app/controllers/dashboard_controller.rb
- app/controllers/offers_controller.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/dashboard_controller_test.rb
- test/controllers/offers_controller_test.rb
Created three controllers; Dashboard, Offers, Bookings
Test..
Look at the controllers in the app file
> Created Controllers

- app/models/offer.rb
- app/models/user.rb
- config/routes.rb
> Routes initial setup

- app/controllers/offers_controller.rb
- app/models/offer.rb
- app/models/user.rb
- app/views/offers/_form.html.erb
- app/views/offers/new.html.erb
- db/migrate/20211123113414_remove_columns_from_offers.rb
- db/migrate/20211123113624_add_columns_to_offers.rb
- db/schema.rb
I created a form partial & rendered in the offer/new view
I did 2 migrations : 1 to remove columns (qty & type) + 1 to add columns (plastic bottles, glass bottles, crates & tip)
I removed the validations in the user model as it was blocking testing and we couldn't pass the login page.
> Offer Form created

- app/models/offer.rb
- app/models/user.rb
- app/views/pages/dashboard.html.erb
- db/seeds.rb
Created seeds and fixed the dashboard
> Updated seeds and dashboard

- app/views/pages/dashboard.html.erb
Fixed the dashboard for a pfander to see if he has confirmed bookings or not
> Created dashboard for pfander

- app/controllers/offers_controller.rb
- app/views/offers/index.html.erb
- config/routes.rb
> bookings controller sharing

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/views/layouts/application.html.erb
- app/views/offers/_form.html.erb
- app/views/pages/home.html.erb
> added search bar

- app/controllers/bookings_controller.rb
- app/javascript/controllers/sweetalert_controller.js
- app/models/booking.rb
- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
- app/views/pages/pfander_dashboard.html.erb
- db/seeds.rb
- package.json
- yarn.lock
Initial Sweetalert setup.
Button working, redirecting to pfander_dashboard
Need to solve issue with displaying the bookings accepted on dashboard
> Bookings creation

- app/controllers/bookings_controller.rb
- app/views/pages/pfander_dashboard.html.erb
- config/routes.rb
fixed the path to display accepted bookings
> fixed accept button to redirect to dashb

- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/javascript/controllers/sweetalert_controller.js
- app/views/layouts/application.html.erb
- app/views/offers/index.html.erb
- app/views/pages/pfander_dashboard.html.erb
- config/routes.rb
- db/seeds.rb
I added a complete button on the pfander dashboard to update the status of the booking to completed.
> fixed the complete button on pfander_dashb

- app/views/layouts/application.html.erb
removed the navbar in the application.html.erb
> removed navbar in app html

- app/views/offers/index.html.erb
- app/views/pages/home.html.erb
added link to offers on search button on home page
> Add button

- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/views/offers/index.html.erb
- app/views/pages/pfander_dashboard.html.erb
- package.json
- yarn.lock
> Card design

- Gemfile.lock
> adds linux arm

- Gemfile
- Gemfile.lock
- app/controllers/offers_controller.rb
- app/javascript/packs/map.js
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/offers/_map_box.html.erb
- app/views/offers/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20211127144058_add_coordinates_to_users.rb
- db/schema.rb
- package.json
- yarn.lock
Added a map on the pfander dashboard
Showing markers on the map
> Added a map with markers for pfanders

- app/views/layouts/application.html.erb
cleaned the code in application.html.erb
> corrected application.html.erb

- app/javascript/components/autocomplete.js
- app/javascript/packs/map.js
- app/views/layouts/application.html.erb
- app/views/offers/index.html.erb
Added the search bar form Bene to the map with autocomplete
> added autocomplete form to the map

- app/javascript/packs/map.js
changed the markers on the map, to show a different icon.
in file app>javascript>packs>map.js
> Changed the markers on the map in map.js

- app/assets/stylesheets/components/_card.scss
- app/views/offers/_show.html.erb
- app/views/pages/donor_dashboard.html.erb
- app/views/pages/pfander_dashboard.html.erb
- db/seeds.rb
> Css dashboard2

- app/controllers/pages_controller.rb
- app/models/offer.rb
- app/views/offers/_show.html.erb
- app/views/offers/index.html.erb
- app/views/pages/donor_dashboard.html.erb
- app/views/pages/pfander_dashboard.html.erb
Fixed the backend logic and some CSS of both user journey pages
> Fixed logic and Dashboard CSS

- app/assets/stylesheets/components/_card.scss
- app/views/offers/_show.html.erb
- app/views/pages/donor_dashboard.html.erb
- app/views/pages/pfander_dashboard.html.erb
- app/views/shared/_footer.html.erb
> Got the sticky footer

- app/controllers/pages_controller.rb
- app/views/pages/donor_dashboard.html.erb
Fixed the donor showing up in the donor dashboard.
Make sure that you have 2 windows open. One that is incognito mode. It was a problem with being signed in as the same user
> Fixed the backend of the dashboard

- app/assets/stylesheets/components/_card.scss
- app/controllers/offers_controller.rb
- app/controllers/pages_controller.rb
- app/views/offers/_show.html.erb
- app/views/offers/edit.html.erb
- app/views/pages/donor_dashboard.html.erb
- app/views/pages/home.html.erb
- app/views/pages/pfander_dashboard.html.erb
The Dashboard is working
Wooohoo!
> The Dashboard is working nice

- app/controllers/offers_controller.rb
- app/javascript/components/autocomplete.js
- app/javascript/packs/map.js
- app/views/offers/_map_box.html.erb
- app/views/offers/index.html.erb
Zoom functionality working with searchbar.
zoom available at city, district and street level
> Map frontend

- db/seeds.rb
> Updating the Seeds

- app/assets/stylesheets/components/_searchbar.scss
- app/views/offers/_show.html.erb
> Fixing the Meta

- app/assets/stylesheets/components/_card.scss
- app/models/user.rb
- app/views/pages/history.html.erb
> History update

- app/assets/stylesheets/components/_avatar.scss
- app/views/pages/history.html.erb
Made history to only be the first 4.
> Fixed the history baby Lets go

- app/views/layouts/application.html.erb
- config/locales/devise.en.yml
> Fixed some bootstrap and devise

- app/javascript/packs/map.js
- app/views/layouts/application.html.erb
> fixing the reload on the map

- app/views/pages/history.html.erb
- config/locales/devise.en.yml
> Fixed this

- app/javascript/packs/map.js
> pns on maps

- app/javascript/packs/map.js
- app/views/layouts/application.html.erb
Added turbolinks tags to the js tags inside the body of the application.html.erb file.(fixed the 2 errors in js, removed the reload script).
Disabled the event listener on the DOMcontent in map.js file as seemed to solve the autocomplete issue.
> fixed reloading issue with the map

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/offers/index.html.erb
- app/views/pages/donor_dashboard.html.erb
- app/views/pages/history.html.erb
- app/views/pages/pfander_dashboard.html.erb
> Fixing the navbar

- app/assets/stylesheets/components/_footer.scss
- app/javascript/controllers/typewriter_controller.js
- app/views/pages/home.html.erb
Created a Javascript Type Writing Effect on the homepage.
> Type writer

- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
> login errors fix
